apiVersion: apps/v1
kind: Deployment
metadata:
  name: railway-bookingreferenceservice

spec:
  replicas: 1
  selector:
    matchLabels:
      app: railway-bookingreferenceservice

  template:
    metadata:
      labels:
        app: railway-bookingreferenceservice
    spec:
      containers:
      - name: railway-bookingreferenceservice
        image: cedricleblond/railwaybookingreferenceservice
        ports:
        - containerPort: 80
          name: bookingref

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: railway-traindataservice

spec:
  replicas: 1
  selector:
    matchLabels:
      app: railway-traindataservice

  template:
    metadata:
      labels:
        app: railway-traindataservice
    spec:
      containers:
      - name: railway-traindataservice
        image: cedricleblond/railwaytraindataservice
        ports:
        - containerPort: 80
          name: traindata

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: traintrain-api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traintrain-api

  template:
    metadata:
      labels:
        app: traintrain-api
    spec:
      containers:
      - name: traintrain-api
        image: cedricleblond/traintrainapi
        ports:
        - containerPort: 80
          name: api

---

apiVersion: v1
kind: Service
metadata:
  name: railway-bookingreferenceservice

spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: railway-bookingreferenceservice

---

apiVersion: v1
kind: Service
metadata:
  name: railway-traindataservice

spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: railway-traindataservice

---

apiVersion: v1
kind: Service
metadata:
  name: traintrain-api

spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: traintrain-api